#!/bin/bash

# Login system information MOTD header

# On Debian you may need to rm /etc/motd && ln -s /var/run/motd /etc/motd

[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ]; then
        # Fall back to using the very slow lsb_release utility
        DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

printf "\033[2J\033[1;1H" #clears the console
printf "\033[1;36m\n" #change the color to cyan + carriage return

# Print the disribution welcome message
printf  "   Welcome to %s! \033[1;30m(%s %s %s)\n" "$DISTRIB_DESCRIPTION" "$(uname -o)" "$(uname -r)" "$(uname -m)"

# Change the color to blue and then print the header ASCII art
printf "\033[0;36m"

echo -e                     "      ___                      ____   __         "
echo -e                     "     / _ \_____    __________ / __/__/ /_______  "
echo -e                     "    / ___/ _ \ |/|/ / -_)/ _ / _// _  / _  / -_) "
echo -e                     "   /_/   \___/__,__/\__,/_/ /___/\_,_/\_, /\__,  "
echo -e "   \033[1;36m                        SomeServer\033[0;36m/___/       "

echo ""
